### ISSUE TITLE
How to get commands from file?

### ISSUE THREAD

**Issue by farcop** [keith/rules_multirun#28]
```
genrule(
    name = "commands_list",
    ...
)

multirun(
    name = "sign",
    commands = ":commands_list",
)
```

I thought it should be easy to do, but commands is a list of strings and I cant understand how to split genrule output to list.

**Comment by keith** [comment]
It's not possible to read files during the analysis phase in bazel. One option instead would be to create a repository_rule that reads the file and generates a BUILD file with each command you want
