### ISSUE TITLE
[FR] print something other than "Running [command target]"

### ISSUE THREAD

**Issue by alexeagle** [keith/rules_multirun#31]
The [`print_command` attribute](https://github.com/keith/rules_multirun/blob/main/multirun.bzl#L133) lets you print something before each command runs, but it's fixed. It would be neat if I could specify a message on the `command` target that should be printed before that command is spawned.
While we're at it, I'd love to be able to print something after the subprocess completes, and have some interpolation variables available like how long it took to run.

**Comment by keith** [comment]
did the first part of this in https://github.com/keith/rules_multirun/pull/35

**Comment by alexeagle** [comment]
Actually I think the second part isn't worth your time. It will be printed at the same time that the program itself completes, so it can just as easily print that output itself.

Thanks!

**Comment by keith** [comment]
sounds good!
