### ISSUE TITLE
[FR] Ability to buffer output rather than interleave

### ISSUE THREAD

**Issue by alexeagle** [keith/rules_multirun#32]
When using `jobs != 1` then commands are run in parallel, and their output steps on each other as they each write bytes to stdout. This makes sense for long-lived servers, but when the commands are short, I'd like an option to buffer their output, then print that output neatly when the command terminates.

**Comment by keith** [comment]
This is a great idea, I don't know why I didn't think of this before. I think the default should probably be this mode and not the interleaving mode, wdyt? that version is done in https://github.com/keith/rules_multirun/pull/36
