### ISSUE TITLE
[Feature Request] It would be nice to pipe stdin - especially to parallel multirun targets

### ISSUE THREAD

**Issue by scottpledger** [keith/rules_multirun#63]
ibazel communicates with executables through stdin, so it would be nice to have multirun pipe stdin to multiple child commands so that rules like `rules_js`'s `js_run_devserver` can properly execute multiple concurrent dev servers.

**Comment by scottpledger** [comment]
Now that this is merged, how would I go about creating a release with these changes?

**Comment by keith** [comment]
https://github.com/keith/rules_multirun/releases/tag/0.10.0
